delete from DICTIONARY_TERMS_RELATIONS where DICTIONARY_TERMS_RELATIONS.term1_id in (select term_id from dictionary_terms where abs(term_text) > 0 and not term_text like '%.%');
delete from DICTIONARY_TERMS_RELATIONS where DICTIONARY_TERMS_RELATIONS.term1_id in (select term_id from dictionary_terms where term_text like 'is' or term_text like 'and' or term_text like 'of' or term_text like 'for' or term_text like 'who' or term_text like 'what' or term_text like 'have' or term_text like 'was' or term_text like 'has' or term_text like 'we' or term_text like 'us' or term_text like 'you' or term_text like 'me');
--delete from DICTIONARY_TERMS_RELATIONS where DICTIONARY_TERMS_RELATIONS.term1_id in (select term_id from dictionary_terms where term_text like '%subject%' or term_text like '%dear%' or term_text like '%r&d%' or term_text like '%floor%' or term_text like '% sp %' or term_text like '%support%' or term_text = 'sp' or term_text like 'but %' or term_text like '%need%' or term_text like '%issue%' or term_text like '%tomorrow%' or term_text like '%poc %'  or term_text like '% fyi %');
--delete from DICTIONARY_TERMS_RELATIONS where DICTIONARY_TERMS_RELATIONS.term1_id in (SELECT term_id FROM dictionary_terms where (term_text like '%sunday%' or  term_text like '%monday%' or term_text like 'mon %' or term_text like '%tuesday%' or term_text like 'tue %' or term_text like '%wednesday%' or term_text like 'wed %' or term_text like '%thursday%' or term_text like 'thu %' or term_text like '%friday%' or term_text like 'fri %' or term_text like '%saturday%' or term_text like 'sat %'));
--delete from DICTIONARY_TERMS_RELATIONS where DICTIONARY_TERMS_RELATIONS.term1_id in (SELECT term_id FROM dictionary_terms where (term_text like '%january%' or  term_text like 'jan %' or  term_text like 'jan.%' or  term_text like '%february%' or  term_text like 'feb %' or  term_text like 'feb.%' or term_text like '%march%' or term_text like 'mar %' or term_text like 'mar.%' or term_text like '%april%' or term_text like 'apr %' or term_text like 'apr.%' or term_text like '%may%' or term_text like '%june%' or term_text like 'jun %' or term_text like 'jun.%' or term_text like '%july%' or term_text like 'jul %' or term_text like 'jul.%' or term_text like '%august%' or term_text like 'aug %' or term_text like 'aug.%' or term_text like '%september%' or term_text like 'sep %' or term_text like 'sep.%' or term_text like '%october%' or term_text like 'oct %' or term_text like 'oct.%' or term_text like '%november%' or term_text like 'nov %' or term_text like 'nov.%' or term_text like '%december%' or term_text like 'dec %' or term_text like 'dec.%'));
--delete from DICTIONARY_TERMS_RELATIONS where DICTIONARY_TERMS_RELATIONS.term1_id in (SELECT term_id FROM dictionary_terms where (term_text like '% mon %' or term_text like '% tue %' or term_text like '% wed %' or term_text like '% thu %' or term_text like '% fri %' or term_text like '% sat %'));
--delete from DICTIONARY_TERMS_RELATIONS where DICTIONARY_TERMS_RELATIONS.term1_id in (SELECT term_id FROM dictionary_terms where (term_text like '% 2007%' or term_text like '% 2008%' or term_text like '% 2009%' or term_text like '% 2010%' or term_text like '% 2011%'));
--delete from DICTIONARY_TERMS_RELATIONS where DICTIONARY_TERMS_RELATIONS.term1_id in (select term_id from dictionary_terms where Length(term_text) < 2);
--delete from DICTIONARY_TERMS_RELATIONS where DICTIONARY_TERMS_RELATIONS.term1_id in (select term_id from dictionary_terms where term_stemmed_text like '%@%.com%');
--delete from DICTIONARY_TERMS_RELATIONS where DICTIONARY_TERMS_RELATIONS.term1_id in (SELECT term_id FROM dictionary_terms where (term_text like '%case%' or term_text like '%problem%' or term_text like '%phone%' or term_text like '%kiss%' or term_text like '%issue%' or term_text like '%awaiting%' or term_text like '%follow%') and term_source_id in (8, 11, 17, 21, 19, 20));
--delete from DICTIONARY_TERMS_RELATIONS where DICTIONARY_TERMS_RELATIONS.term1_id in (SELECT term_id FROM dictionary_terms where (term_text like '% thx %' or term_text like 'thx' or term_text like '% pls %' or term_text like 'pls' or term_text like '% btw %' or term_text like 'btw' or term_text like 'can''t'));
--delete from DICTIONARY_TERMS_RELATIONS where DICTIONARY_TERMS_RELATIONS.term1_id in (SELECT term_id FROM dictionary_terms where (term_text like '%webex%' or term_text like '%customer%' or term_text like 'hotfix'  or term_text like 'emea' or term_text like 'oem' or term_text like 'poc'));
--delete from DICTIONARY_TERMS_RELATIONS where DICTIONARY_TERMS_RELATIONS.term1_id in (SELECT term_id FROM dictionary_terms where (term_text like '%<font%' or term_text like '%verdana%' or term_text like '%font-%' or term_text like '%sant-serif%' or term_text like '%background-%' or term_text like '%margin-%'));

delete from DICTIONARY_TERMS where DICTIONARY_TERMS.term_id in (select term_id from dictionary_terms where abs(term_text) > 0 and not term_text like '%.%');
delete from DICTIONARY_TERMS where DICTIONARY_TERMS.term_id in (select term_id from dictionary_terms where term_text like 'is' or term_text like 'and' or term_text like 'of' or term_text like 'for' or term_text like 'who' or term_text like 'what' or term_text like 'have' or term_text like 'was' or term_text like 'has' or term_text like 'we' or term_text like 'us' or term_text like 'you' or term_text like 'me');
--delete from DICTIONARY_TERMS where DICTIONARY_TERMS.term_id in (select term_id from dictionary_terms where term_text like '%subject%' or term_text like '%dear%' or term_text like '%r&d%' or term_text like '%floor%' or term_text like '% sp %' or term_text like '%support%' or term_text = 'sp'  or term_text like 'but %' or term_text like '%need%' or term_text like '%issue%'  or term_text like '%tomorrow%' or term_text like '%poc %' or term_text like '% fyi %');
--delete from DICTIONARY_TERMS where DICTIONARY_TERMS.term_id in (SELECT term_id FROM dictionary_terms where (term_text like '%sunday%' or  term_text like '%monday%' or term_text like 'mon %' or term_text like '%tuesday%' or term_text like 'tue %' or term_text like '%wednesday%' or term_text like 'wed %' or term_text like '%thursday%' or term_text like 'thu %' or term_text like '%friday%' or term_text like 'fri %' or term_text like '%saturday%' or term_text like 'sat %'));
--delete from DICTIONARY_TERMS where DICTIONARY_TERMS.term_id in (SELECT term_id FROM dictionary_terms where (term_text like '%january%' or  term_text like 'jan %' or  term_text like 'jan.%' or  term_text like '%february%' or  term_text like 'feb %' or  term_text like 'feb.%' or term_text like '%march%' or term_text like 'mar %' or term_text like 'mar.%' or term_text like '%april%' or term_text like 'apr %' or term_text like 'apr.%' or term_text like '%may%' or term_text like '%june%' or term_text like 'jun %' or term_text like 'jun.%' or term_text like '%july%' or term_text like 'jul %' or term_text like 'jul.%' or term_text like '%august%' or term_text like 'aug %' or term_text like 'aug.%' or term_text like '%september%' or term_text like 'sep %' or term_text like 'sep.%' or term_text like '%october%' or term_text like 'oct %' or term_text like 'oct.%' or term_text like '%november%' or term_text like 'nov %' or term_text like 'nov.%' or term_text like '%december%' or term_text like 'dec %' or term_text like 'dec.%'));
--delete from DICTIONARY_TERMS where DICTIONARY_TERMS.term_id in (SELECT term_id FROM dictionary_terms where (term_text like '% mon %' or term_text like '% tue %' or term_text like '% wed %' or term_text like '% thu %' or term_text like '% fri %' or term_text like '% sat %'));
--delete from DICTIONARY_TERMS where DICTIONARY_TERMS.term_id in (SELECT term_id FROM dictionary_terms where (term_text like '% 2007%' or term_text like '% 2008%' or term_text like '% 2009%' or term_text like '% 2010%' or term_text like '% 2011%'));
--delete from DICTIONARY_TERMS where DICTIONARY_TERMS.term_id in (select term_id from dictionary_terms where term_stemmed_text like '%@%.com%');
--delete from DICTIONARY_TERMS where DICTIONARY_TERMS.term_id in (SELECT term_id FROM dictionary_terms where (term_text like '%case%' or term_text like '%problem%' or term_text like '%phone%' or term_text like '%issue%' or term_text like '%awaiting%' or term_text like '%follow%') and term_source_id in (8, 11, 17, 21, 19, 20));
--delete from DICTIONARY_TERMS where DICTIONARY_TERMS.term_id in (SELECT term_id FROM dictionary_terms where (term_text like '% thx %' or term_text like 'thx' or term_text like '% pls %' or term_text like 'pls' or term_text like '% btw %' or term_text like 'btw' or term_text like 'can''t'));
--delete from DICTIONARY_TERMS where DICTIONARY_TERMS.term_id in (SELECT term_id FROM dictionary_terms where (term_text like '%webex%' or term_text like '%customer%' or term_text like 'hotfix' or term_text like 'emea' or term_text like 'oem' or term_text like 'poc'));
--delete from DICTIONARY_TERMS where DICTIONARY_TERMS.term_id in (SELECT term_id FROM dictionary_terms where (term_text like '%<font%' or term_text like '%verdana%' or term_text like '%font-%' or term_text like '%sant-serif%' or term_text like '%background-%' or term_text like '%margin-%'));

delete from DICTIONARY_TERMS where DICTIONARY_TERMS.term_id in (select term_id from dictionary_terms where Length(term_text) < 2);

update dictionary_terms set term_source_id = 23 where term_source_id = 12 and (term_text like '%-%' and term_text not like '-%');
update dictionary_terms set term_source_id = 14 where term_source_id = 22 and term_text like 'com.%';

update dictionary_terms set term_source_id = 44 where term_source_id = 103 and (term_extraction_methods = 'Non English Words, NLP NNP Tokens Single Split' or term_extraction_methods = 'NLP NNP Tokens Single Split, Non English Words');
update dictionary_terms set term_source_id = 103 where term_source_id = 17 and term_text not like '% %'; 
--update dictionary_terms set term_status = 1 where term_source_id in (4, 44); 
--update dictionary_terms set term_status = 1 where term_status = 0 and term_frequency > 25 and term_tickets not like '%,%' and term_source_id <> 101; 

delete from dictionary_terms_relations where term1_id not in (select term_id from dictionary_terms);
delete from dictionary_terms_relations where term2_id not in (select term_id from dictionary_terms);
